/* Learning case studies: curated from the linked public project READMEs.
   Charts are copies of repository assets; diagrams are labeled editorial summaries. */
const learningRepo = name => `https://github.com/swatibansal/${name}`;
const learningFigure = (file, alt, caption, repo, source) => `<figure class="case-figure"><img src="assets/learning/${file}" alt="${alt}" loading="lazy"><figcaption>${caption} <a href="${learningRepo(repo)}/blob/main/${source}" target="_blank" rel="noopener noreferrer">Original project figure ↗</a></figcaption></figure>`;
const learningDiagram = (label, items) => `<figure class="case-figure"><div class="case-diagram"><div class="case-diagram-label">CONCEPTUAL GUIDE</div><div class="case-diagram-grid">${items.map(([title, text]) => `<div class="case-diagram-item"><strong>${title}</strong><p>${text}</p></div>`).join('')}</div></div><figcaption>${label} Editorial summary of the implementation; not a measured result.</figcaption></figure>`;
const learningStudy = ({ title, repo, tags, body, demo }) => ({
 title, label: 'LEARNING THROUGH BUILDING · CASE STUDY',
 body: `<div class="chips" aria-label="Project topics">${tags.map(tag => `<span>${tag}</span>`).join('')}</div>${body}<div class="case-actions"><a class="button primary" href="${learningRepo(repo)}" target="_blank" rel="noopener noreferrer">View repository <span aria-hidden="true"> ↗</span></a>${demo ? `<a class="text-link" href="${demo}" target="_blank" rel="noopener noreferrer">Explore live project ↗</a>` : ''}</div><p class="case-source">Source: <a href="${learningRepo(repo)}/blob/main/README.md" target="_blank" rel="noopener noreferrer">project README, methodology, and reproduction steps</a>. Results below describe the repository’s reported experiments.</p>`
});
const learningCases = {
 'case-tokenizer': learningStudy({
  title: 'Multilingual BPE tokenizer', repo: 'bpe-fairness-tokenizer', tags: ['Tokenization', 'Multilingual AI', 'Vocabulary trade-offs'],
  body: `<p>Before a language model can read text, a tokenizer turns it into token IDs. I built a multilingual tokenizer to understand how those representation choices affect different scripts and the token budgets that applications must manage.</p><h3>The problem</h3><p>A shared vocabulary has limited room. How it allocates that room across languages affects token counts, while careless character splitting can break meaningful combinations in Indic scripts.</p>${learningDiagram('From text to a shared vocabulary.', [ ['1 · Preserve text structure', 'Normalize Unicode and identify grapheme clusters, keeping related characters together.'], ['2 · Learn useful merges', 'Build a shared BPE vocabulary across English, Hindi, Telugu, and Bengali.'], ['3 · Inspect the trade-off', 'Compare tokens per evaluation unit and see where vocabulary capacity is spent.'], ['4 · Check the round trip', 'Decode token IDs and test visible-character preservation, including fallback behavior.'] ])}<h3>What I built</h3><p>A Python tokenizer with an approximately 10,000-token shared vocabulary, byte fallback, robustness tests, and a browser playground that exposes token boundaries and decoding.</p><h3>What the experiment shows</h3><p>The project compares compression across four languages and makes vocabulary allocation visible. Its tests cover cases such as mixed scripts, punctuation, emoji, and serialization.</p><h3>The enterprise connection</h3><p>Representation is an engineering contract. Inspect token counts and round-trip behavior on the languages your application actually serves before assuming equal context capacity or predictable usage.</p><p class="case-note">The reported compression metrics use the project’s evaluation corpus; they do not establish performance on every language or unseen domain. Whitespace is normalized, and the literal metaspace marker has a documented round-trip limitation.</p>`
 }),
 'case-attention': learningStudy({
  title: 'The evolution of attention', repo: 'attention-llm-timeline', tags: ['Attention', 'Memory & compute', 'Architecture trade-offs'], demo: 'https://attention-llm-timeline.netlify.app/',
  body: `<p>I approached attention’s evolution as a sequence of engineering decisions: what constraint appeared, what changed, and what did that change cost?</p><h3>The problem</h3><p>Longer sequences and growing inference state place pressure on compute, memory capacity, and data movement. Understanding which bottleneck a technique addresses helps explain why architectures evolve.</p>${learningDiagram('Different constraints lead to different design choices.', [ ['Pairwise work', 'Sparse and windowed attention restrict which token pairs interact.'], ['Memory movement', 'FlashAttention changes how exact attention is computed to reduce costly memory traffic.'], ['Inference state', 'Multi-query and grouped-query attention share key/value representations across query heads.'], ['Position and context', 'Position encodings and context-extension methods address how token positions are represented.'] ])}<h3>What I built</h3><p>An interactive research timeline with primary-source links, pros and cons, and guidance on when each mechanism is useful. Plain-language analogies sit alongside the technical descriptions.</p><h3>The decisions that matter</h3><p>The project separates publication chronology from adoption and flags exceptions to its date policy. Its validation checks enforce ordering and require trade-offs rather than presenting each newer mechanism as an unconditional improvement.</p><h3>The enterprise connection</h3><p>Start with the constraint before selecting an optimization. The same discipline applies when evaluating database indexes, caching strategies, or distributed coordination: name the bottleneck and make the new cost explicit.</p><p class="case-note">This is a sourced learning timeline, not a performance benchmark or a ranking of production models. The conceptual guide groups techniques by purpose; it is not the chronological timeline.</p>`
 }),
 'case-zero': learningStudy({
  title: 'What should every worker keep?', repo: 'zero-simulation-llm', tags: ['ZeRO', 'State sharding', 'Distributed systems'], demo: 'https://swatibansal.github.io/zero-simulation-llm/',
  body: `<p>A familiar distributed-systems question sits inside large-model training: which state should every worker replicate, and which state can workers share?</p><h3>The problem</h3><p>Replicating parameters, gradients, and optimizer state on every worker consumes memory. Sharding reduces duplication, but some state must then be communicated before it can be used.</p><h3>What I built</h3><p>A NumPy simulation of 32 virtual GPUs comparing data parallelism with ZeRO stages 1, 2, and 3. Explicit memory ledgers and ring collectives expose where bytes live and when they move.</p>${learningFigure('zero-memory.png','Bar chart comparing per-worker peak memory across data parallelism and ZeRO stages 1, 2, and 3.','The simulator reports peak memory falling from 52.2 MB per worker for data parallelism to 5.7 MB for ZeRO-3 in this configuration.','zero-simulation-llm','figures/peak_memory_by_stage.png')}<h3>What the experiment shows</h3><p>The reported run keeps weights identical across the four strategies. ZeRO changes state ownership while preserving the computation in this simulation. Temporary gathered layers and gradient buffers also explain why peak memory exceeds persistent-state estimates.</p>${learningFigure('zero-communication.png','Chart comparing reduce-scatter and all-gather communication volume for each sharding stage.','The memory saving has a coordination cost: the simulated ZeRO-3 configuration communicates about 1.5 times the bytes of the data-parallel baseline.','zero-simulation-llm','figures/comm_volume.png')}<h3>The enterprise connection</h3><p>Sharding a system can solve capacity without solving latency. Choose an ownership strategy by considering peak memory, communication, and the slowest participant together.</p><p class="case-note">These are CPU-simulator results, not measurements from a physical GPU cluster. Hardware timing estimates are modeled; the observed weight equivalence is specific to the implementation and experiment.</p>`
 }),
 'case-training-recovery': learningStudy({
  title: 'What happens when training crashes?', repo: 'training-execution-system', tags: ['Checkpointing', 'Deterministic replay', 'Data provenance'],
  body: `<p>Saving a model is only part of recovery. I built a small training-data execution system to make the rest explicit: the input history, commit boundary, loader position, and evidence that resume picked up the intended work.</p><h3>The problem</h3><p>After a crash, a checkpoint alone does not describe every batch consumed since it was written. Recovery needs a consistent relationship between model state and the data execution history.</p>${learningDiagram('The recovery contract.', [ ['Inputs · immutable shards', 'Hashes and manifests identify the data admitted to the run.'], ['Commit · recorded progress', 'Append-only ledgers record consumed batches and learning results after the optimizer step.'], ['Resume · restore and replay', 'Restore model, optimizer, RNG, and loader state; regenerate steps after the checkpoint.'], ['Verify · compare evidence', 'Check regenerated batch hashes against the ledger and recompute audit verdicts from artifacts.'] ])}<h3>What I built</h3><p>A complete synthetic-data run through tokenization, shard validation, evaluation separation, mixture scheduling, document packing, training, an intentional subprocess crash, verified resume, replay, and a branched run.</p><h3>What the experiment shows</h3><p>The project recomputes its audit outcomes from saved artifacts. Resume and replay compare expected and regenerated batch identities rather than treating a successful process restart as proof of correctness.</p><h3>The enterprise connection</h3><p>This is the same reasoning used around stream offsets and durable processing: identify the commit point, capture enough state to recover, and verify replay against recorded history.</p><p class="case-note">The project demonstrates deterministic recovery for a small, controlled setup with synthetic data. It does not establish exactly-once behavior for arbitrary distributed training jobs or external side effects.</p>`
 }),
 'case-training-metrics': learningStudy({
  title: 'Can you trust the training metric?', repo: 'training-loop-internals', tags: ['Observability', 'Gradient accumulation', 'Correctness'],
  body: `<p>A training loop can run successfully while calculating the wrong aggregate. I opened up a small transformer to inspect the shapes, gradients, and measurements behind its learning curve.</p><h3>The problem</h3><p>When micro-batches contain different numbers of tokens, averaging their averages gives unequal weight to individual tokens. A plausible loss curve can hide this accounting mistake.</p><h3>What I built</h3><p>Six experiments around a small transformer: named tensor dimensions, a finite-difference gradient check, deliberately incorrect accumulation, gradient-norm monitoring, utilization accounting, and floating-point representation.</p>${learningFigure('training-aggregation.png','Training curves comparing token-weighted gradient accumulation with incorrect averaging across unequal micro-batches.','The paired experiment uses the same seed and evaluation metric. Its reported final losses are approximately 1.88 for correct accumulation and 2.05 for the broken version.','training-loop-internals','outputs/part3_accumulation_bug.png')}<h3>What the experiment shows</h3><p>Correct weighting matters before performance tuning. The project also checks an autograd result against a numerical derivative and observes the response to an intentionally corrupted batch.</p><h3>The enterprise connection</h3><p>Metric denominators are part of correctness. The same mistake appears when equally averaging service-level averages from services with unequal traffic. Instrument the computation and verify what each measurement represents.</p><p class="case-note">These results come from a small-model experiment. A gradient spike observed before a loss peak is not a universal early-warning guarantee, and CPU utilization measurements are not production GPU benchmarks.</p>`
 }),
 'case-foundations': learningStudy({
  title: 'What does a model actually learn?', repo: 'deep-learning-patterns', tags: ['Neural networks', 'Embeddings', 'Generalization'],
  body: `<p>I started with four small, visual experiments to connect unfamiliar deep-learning concepts to questions I already ask about software: what can this abstraction express, and what evidence says it works beyond the examples I gave it?</p><h3>The problem</h3><p>Terms such as depth, embeddings, and generalization can feel abstract until we isolate one idea at a time and observe the result.</p><h3>What I built</h3><p>Four PyTorch experiments compare linear and nonlinear models, collapse stacked linear layers into one transformation, inspect learned embedding neighborhoods, and measure the gap between training and test performance.</p>${learningFigure('nonlinearity.png','Decision-boundary experiment on concentric rings comparing a linear model and a model with a ReLU layer.','Nonlinearity changes what the model can express on the concentric-ring task. Adding only linear layers does not provide the same capability.','deep-learning-patterns','assets/s1_1.png')}${learningFigure('learned-embeddings.png','Visualization of learned embeddings for a tiny grammar with animal, verb, and fruit categories.','The toy next-token task produces category structure without explicit similarity labels. This is an observed result in the controlled grammar.','deep-learning-patterns','assets/s1_3.png')}<h3>The enterprise connection</h3><p>More components do not automatically create a more capable system. Evaluate the behavior an architecture enables, and distinguish success on known examples from performance on held-out inputs.</p><p class="case-note">These controlled experiments introduce foundational ideas. Their accuracy and clustering results do not predict real-world language-model performance. Start here if you are new to deep learning.</p>`
 })
};
